feat: support ESLint 8.x
dangreenisrael/eslint-plugin-jest-formatting pull request #108
Opened 2021-08-29 15:10 UTC by MichaelDeBoey

ESLint has released the first beta versions of v8 🎉
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.1-released

devDependency compatibility with ESLint 8:

- [ ] [`@typescript-eslint/eslint-plugin`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) (https://github.com/typescript-eslint/typescript-eslint/issues/3738)
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/2933
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3737
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3767
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3768
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3800
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3806
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3808
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/3809
  - [ ] Release
- [ ] [`@typescript-eslint/parser`](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser) (https://github.com/typescript-eslint/typescript-eslint/issues/3738)
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/2933
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3737
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3767
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3768
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3800
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3806
  - [x] https://github.com/typescript-eslint/typescript-eslint/pull/3808
  - [ ] https://github.com/typescript-eslint/typescript-eslint/pull/3809
  - [ ] Release
- [ ] [`eslint-config-airbnb-base`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) (https://github.com/airbnb/javascript/issues/2463)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) (https://github.com/prettier/eslint-config-prettier/issues/200)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) (https://github.com/import-js/eslint-plugin-import/issues/2211)
  - [ ] https://github.com/import-js/eslint-plugin-import/pull/2191
  - [ ] Release
- [ ] [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest) (https://github.com/jest-community/eslint-plugin-jest/issues/881)
  - [ ] https://github.com/jest-community/eslint-plugin-jest/pull/882
  - [ ] Release
- [ ] [`eslint-plugin-jest-formatting`](https://github.com/dangreenisrael/eslint-plugin-jest-formatting) (https://github.com/dangreenisrael/eslint-plugin-jest-formatting/issues/107)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier) (https://github.com/prettier/eslint-plugin-prettier/issues/427)
  - [ ] https://github.com/prettier/eslint-plugin-prettier/pull/428
  - [ ] Release

---

Closes #107

2021-08-31 15:13 UTC, benkimpel commented
@MichaelDeBoey Thanks for the PR. Need any help? (I know it's still in Draft, but couldn't help taking a look.)

2021-08-31 15:29 UTC, MichaelDeBoey commented
@benkimpel I think I'm mostly waiting on the devDeps to support ESLint 8.x now 🤔

2021-08-31 18:35 UTC, benkimpel commented
> @benkimpel I think I'm mostly waiting on the devDeps to support ESLint 8.x now thinking

Great! :+1:

2021-11-09 17:28 UTC, dangreenisrael commented
Hey @MichaelDeBoey, you have some linting errors

2021-11-09 17:42 UTC, MichaelDeBoey commented
@dangreenisrael Should I just ignore `no-shadow` rule on these lines?
They're reporting that i's already there on their own line

```sh
18:19  error  'StatementType' is already declared in the upper scope on line 18 column 19  no-shadow
40:19  error  'PaddingType' is already declared in the upper scope on line 40 column 19    no-shadow
```

2021-11-10 19:39 UTC, dangreenisrael commented
I think I'm cool with that. Will you just add a comment in the code explaining why we are making an exception to the rule?

2021-11-15 09:18 UTC, Belco90 requested changes

2021-11-15 09:18 UTC, Belco90 commented on package.json
> +    "eslint": "^8.2.0",
Sticking to ESLint v7 in the dev dependencies would unblock this PR could (not really sure where the compatibility with ESLint v8 is added/tested in this PR repo). Upgrading ESLint here is just for the local environment used to develop the project, that must not block this PR to add ESLint v8 compatibility to the package.

2021-11-15 18:35 UTC, benkimpel commented on src/rules/padding.ts
> +// eslint-disable-next-line no-shadow
https://github.com/typescript-eslint/typescript-eslint/issues/2484#issuecomment-687257773
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md

@dangreenisrael @MichaelDeBoey The fix for this is to update the project's linting config as described in links above. It's an erroneous no-shadow error in this case. We should have been using the typescript no-shadow rule. Sorry about that @MichaelDeBoey... probably seemed pretty weird to see it shadowing itself on the same line.

2021-11-15 18:55 UTC, benkimpel commented on src/rules/padding.ts
> +// eslint-disable-next-line no-shadow
(My mistake originally. Shame!)

2021-11-16 04:12 UTC, benkimpel approved these changes
LGTM. Thank you! :pray:

2021-11-16 04:17 UTC, benkimpel commented
@MichaelDeBoey I want to give @dangreenisrael a chance to review, but this will probably merge tomorrow.

2021-11-16 23:25 UTC, benkimpel commented
> @MichaelDeBoey I want to give @dangreenisrael a chance to review, but this will probably merge tomorrow.

I'm going to take Dan's [comment](https://github.com/dangreenisrael/eslint-plugin-jest-formatting/pull/108#issuecomment-965678299) as tacit approval for a merge. He'll have to trigger the release to npm, though.

2021-11-16 23:25 UTC, merged

2021-11-17 09:25 UTC, MichaelDeBoey commented
@dangreenisrael Can you please trigger the release?

2021-11-17 22:22 UTC, dangreenisrael commented
`3.1.0` has been shipped. Thanks so much for your work @MichaelDeBoey!